In [1]:
import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
URL="https://github.com/ageron/handson-ml2/blob/master/datasets/housing/housing.csv?raw=true"
df=pd.read_csv(URL)
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [4]:
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(df, test_size=0.2, random_state=35)
train_set

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
1380     -122.09     38.00                 6.0      10191.0          1882.0   
12294    -116.93     33.93                13.0       7804.0          1594.0   
7387     -118.25     33.97                37.0        794.0           210.0   
14454    -117.27     32.83                39.0       1877.0           426.0   
2927     -119.01     35.36                24.0       1941.0           484.0   
...          ...       ...                 ...          ...             ...   
19391    -120.85     37.78                25.0        421.0             NaN   
15393    -116.90     33.22                11.0       4132.0           773.0   
9143     -117.96     34.48                32.0       1896.0           342.0   
17679    -121.84     37.32                22.0       3015.0           581.0   
5833     -118.32     34.20                36.0       1978.0           337.0   

       population  households  median_income  median_house_value  \
1380       4377.0      1789.0         5.2015            204200.0   
12294      3297.0      1469.0         2.0549             95600.0   
7387        814.0       213.0         2.2917            112000.0   
14454       805.0       409.0         3.8750            410000.0   
2927       1277.0       435.0         1.0560             51600.0   
...           ...         ...            ...                 ...   
19391       303.0       106.0         2.2679             71300.0   
15393      2012.0       703.0         3.1906            234500.0   
9143        806.0       299.0         4.5769            159400.0   
17679      2491.0       530.0         4.3419            176300.0   
5833        834.0       311.0         3.9866            294400.0   

      ocean_proximity  
1380         NEAR BAY  
12294          INLAND  
7387        <1H OCEAN  
14454      NEAR OCEAN  
2927           INLAND  
...               ...  
19391          INLAND  
15393       <1H OCEAN  
9143           INLAND  
17679       <1H OCEAN  
5833        <1H OCEAN  

[16512 rows x 10 columns]

In [5]:
housing=train_set.drop("median_house_value", axis=1)
housing_labels=train_set["median_house_value"].copy

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [7]:
#1-Nan qatorlani tashlab yuborish
housing.dropna(subset=['total_bedrooms'])

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
1380     -122.09     38.00                 6.0      10191.0          1882.0   
12294    -116.93     33.93                13.0       7804.0          1594.0   
7387     -118.25     33.97                37.0        794.0           210.0   
14454    -117.27     32.83                39.0       1877.0           426.0   
2927     -119.01     35.36                24.0       1941.0           484.0   
...          ...       ...                 ...          ...             ...   
15808    -122.44     37.76                52.0       2509.0           496.0   
15393    -116.90     33.22                11.0       4132.0           773.0   
9143     -117.96     34.48                32.0       1896.0           342.0   
17679    -121.84     37.32                22.0       3015.0           581.0   
5833     -118.32     34.20                36.0       1978.0           337.0   

       population  households  median_income ocean_proximity  
1380       4377.0      1789.0         5.2015        NEAR BAY  
12294      3297.0      1469.0         2.0549          INLAND  
7387        814.0       213.0         2.2917       <1H OCEAN  
14454       805.0       409.0         3.8750      NEAR OCEAN  
2927       1277.0       435.0         1.0560          INLAND  
...           ...         ...            ...             ...  
15808       855.0       478.0         5.0731        NEAR BAY  
15393      2012.0       703.0         3.1906       <1H OCEAN  
9143        806.0       299.0         4.5769          INLAND  
17679      2491.0       530.0         4.3419       <1H OCEAN  
5833        834.0       311.0         3.9866       <1H OCEAN  

[16346 rows x 9 columns]

In [8]:
housing.drop("total_bedrooms", axis=1)

longitude  latitude  housing_median_age  total_rooms  population  \
1380     -122.09     38.00                 6.0      10191.0      4377.0   
12294    -116.93     33.93                13.0       7804.0      3297.0   
7387     -118.25     33.97                37.0        794.0       814.0   
14454    -117.27     32.83                39.0       1877.0       805.0   
2927     -119.01     35.36                24.0       1941.0      1277.0   
...          ...       ...                 ...          ...         ...   
19391    -120.85     37.78                25.0        421.0       303.0   
15393    -116.90     33.22                11.0       4132.0      2012.0   
9143     -117.96     34.48                32.0       1896.0       806.0   
17679    -121.84     37.32                22.0       3015.0      2491.0   
5833     -118.32     34.20                36.0       1978.0       834.0   

       households  median_income ocean_proximity  
1380       1789.0         5.2015        NEAR BAY  
12294      1469.0         2.0549          INLAND  
7387        213.0         2.2917       <1H OCEAN  
14454       409.0         3.8750      NEAR OCEAN  
2927        435.0         1.0560          INLAND  
...           ...            ...             ...  
19391       106.0         2.2679          INLAND  
15393       703.0         3.1906       <1H OCEAN  
9143        299.0         4.5769          INLAND  
17679       530.0         4.3419       <1H OCEAN  
5833        311.0         3.9866       <1H OCEAN  

[16512 rows x 8 columns]

In [9]:
median=housing['total_bedrooms'].median()
median

434.0

In [12]:
housing['total_bedrooms'].fillna(median)


longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
1380     -122.09     38.00                 6.0      10191.0          1882.0   
12294    -116.93     33.93                13.0       7804.0          1594.0   
7387     -118.25     33.97                37.0        794.0           210.0   
14454    -117.27     32.83                39.0       1877.0           426.0   
2927     -119.01     35.36                24.0       1941.0           484.0   
...          ...       ...                 ...          ...             ...   
19391    -120.85     37.78                25.0        421.0             NaN   
15393    -116.90     33.22                11.0       4132.0           773.0   
9143     -117.96     34.48                32.0       1896.0           342.0   
17679    -121.84     37.32                22.0       3015.0           581.0   
5833     -118.32     34.20                36.0       1978.0           337.0   

       population  households  median_income ocean_proximity  
1380       4377.0      1789.0         5.2015        NEAR BAY  
12294      3297.0      1469.0         2.0549          INLAND  
7387        814.0       213.0         2.2917       <1H OCEAN  
14454       805.0       409.0         3.8750      NEAR OCEAN  
2927       1277.0       435.0         1.0560          INLAND  
...           ...         ...            ...             ...  
19391       303.0       106.0         2.2679          INLAND  
15393      2012.0       703.0         3.1906       <1H OCEAN  
9143        806.0       299.0         4.5769          INLAND  
17679      2491.0       530.0         4.3419       <1H OCEAN  
5833        834.0       311.0         3.9866       <1H OCEAN  

[16512 rows x 9 columns]

In [13]:
from sklearn.impute import SimpleImputer

In [19]:
imputer=SimpleImputer(strategy='median')

In [20]:
housing_num = housing.drop('ocean_proximity', axis=1)
imputer.fit(housing_num)

SimpleImputer(strategy='median')

In [21]:
imputer.statistics_

array([-118.495 ,   34.26  ,   29.    , 2120.5   ,  434.    , 1168.5   ,
        408.    ,    3.5338])

In [22]:
X=imputer.transform(housing_num)

In [23]:
housing_tr=pd.DataFrame(X, columns = housing_num.columns, index = housing_num.index)

In [24]:
housing_tr.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16512 entries, 1380 to 5833
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           16512 non-null  float64
 1   latitude            16512 non-null  float64
 2   housing_median_age  16512 non-null  float64
 3   total_rooms         16512 non-null  float64
 4   total_bedrooms      16512 non-null  float64
 5   population          16512 non-null  float64
 6   households          16512 non-null  float64
 7   median_income       16512 non-null  float64
dtypes: float64(8)
memory usage: 1.1 MB


In [27]:
housing_num.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16512 entries, 1380 to 5833
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           16512 non-null  float64
 1   latitude            16512 non-null  float64
 2   housing_median_age  16512 non-null  float64
 3   total_rooms         16512 non-null  float64
 4   total_bedrooms      16346 non-null  float64
 5   population          16512 non-null  float64
 6   households          16512 non-null  float64
 7   median_income       16512 non-null  float64
dtypes: float64(8)
memory usage: 1.1 MB


In [28]:
housing_cat=housing[['ocean_proximity']]

In [29]:
housing_cat.value_counts()

ocean_proximity
<1H OCEAN          7313
INLAND             5218
NEAR OCEAN         2110
NEAR BAY           1866
ISLAND                5
Name: count, dtype: int64

In [33]:
from sklearn.preprocessing import OneHotEncoder

In [34]:
cat_encoder = OneHotEncoder()
housing_cat_1hot = cat_encoder.fit_transform(housing_cat)
housing_cat_1hot.toarray()

array([[0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       ...,
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [38]:
from sklearn.base import BaseEstimator, TransformerMixin
rooms_ix, bedrooms_ix, population_ix, households_ix=3, 4, 5, 6

class CombinedAttributesAdder(BaseEstimator, TransformerMixin):
  def __init__(self, add_bedrooms_per_room = True):
    self.add_bedrooms_per_room = add_bedrooms_per_room
  def fit(self, X):
    return self
  def transform(self, X):
    rooms_per_household= X[:,rooms_ix] /X[:,households_ix]
    population_per_household= X[:,population_ix] /X[:,households_ix]
    if self.add_bedrooms_per_room:
      bedrooms_per_room = X[:, bedrooms_ix]/X[:,rooms_ix]
      return np.c_[X,rooms_per_household, population_per_household, bedrooms_per_room]
    else:
      return np.c_[X, rooms_per_household, population_per_household]

In [45]:
attr_adder=CombinedAttributesAdder()
housing_extra_attribs = attr_adder.transform(housing.values)

In [46]:
housing_extra_attribs[0:]

array([[-122.09, 38.0, 6.0, ..., 'NEAR BAY', 5.69647847959754,
        2.446618222470654],
       [-116.93, 33.93, 13.0, ..., 'INLAND', 5.312457454050374,
        2.2443839346494214],
       [-118.25, 33.97, 37.0, ..., '<1H OCEAN', 3.727699530516432,
        3.8215962441314555],
       ...,
       [-117.96, 34.48, 32.0, ..., 'INLAND', 6.34113712374582,
        2.6956521739130435],
       [-121.84, 37.32, 22.0, ..., '<1H OCEAN', 5.688679245283019, 4.7],
       [-118.32, 34.2, 36.0, ..., '<1H OCEAN', 6.360128617363344,
        2.6816720257234725]], dtype=object)

In [47]:
from sklearn.preprocessing import MinMaxScaler

min_max_scaler = MinMaxScaler()

min_max_scaler.fit_transform(housing_num)

array([[0.2250996 , 0.58023379, 0.09803922, ..., 0.12259312, 0.29403059,
        0.3242438 ],
       [0.73904382, 0.1477152 , 0.23529412, ..., 0.09232322, 0.24140766,
        0.1072399 ],
       [0.60756972, 0.15196599, 0.70588235, ..., 0.02273046, 0.03486269,
        0.12357071],
       ...,
       [0.63645418, 0.20616366, 0.60784314, ..., 0.02250624, 0.0490051 ,
        0.28116854],
       [0.25      , 0.50797024, 0.41176471, ..., 0.0697329 , 0.08699227,
        0.26496186],
       [0.60059761, 0.17640808, 0.68627451, ..., 0.02329101, 0.05097846,
        0.24045875]])

In [48]:
from sklearn.preprocessing import StandardScaler

standard_scaler = StandardScaler()

standard_scaler.fit_transform(housing_num)

array([[-1.25390838,  1.10757958, -1.79230424, ...,  2.57514612,
         3.36084902,  0.69829788],
       [ 1.31649014, -0.79863258, -1.2367069 , ...,  1.63187609,
         2.52702704, -0.9522322 ],
       [ 0.65894633, -0.77989831,  0.66819829, ..., -0.53677157,
        -0.74572422, -0.82802018],
       ...,
       [ 0.80340671, -0.54103634,  0.27134305, ..., -0.54375875,
        -0.52163456,  0.37066771],
       [-1.12937357,  0.78909696, -0.52236745, ...,  0.92791716,
         0.08028068,  0.24739988],
       [ 0.62407658, -0.67217624,  0.58882724, ..., -0.51930361,
        -0.49036624,  0.0610294 ]])