<a href="https://colab.research.google.com/github/Xasan17/lessons_python/blob/main/mohirdev_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [1]:
import numpy as np
np.__version__
np.show_config()


Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139863411681952
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    versio

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [5]:
list1=list(range(10))
arr=np.array(list1)
print(arr)
#arr=np.array([0,1,2,3,4,5,6,7,8,9])

[0 1 2 3 4 5 6 7 8 9]


#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

In [10]:
zer0=np.zeros((1,9))
print(zer0)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [16]:
arr=np.arange(10)
size=arr.size
itemsize=arr.itemsize
total=size*itemsize
print(f'Masivning hotira hajmi {total} ga teng')

Masivning hotira hajmi 80 ga teng


#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [17]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [20]:
vektor=np.array([0]*12)
vektor[5]=1
print(vektor)

[0 0 0 0 0 1 0 0 0 0 0 0]


#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [22]:
vektor=np.arange(20,59,1)
print(vektor)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58]


#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [24]:
vektor=np.arange(20,59,1)
teskari_vektor=vektor[::-1]
print(teskari_vektor)

[58 57 56 55 54 53 52 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35
 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20]


#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [28]:
arr2d=np.arange(12,21,1).reshape(3,3)
print(arr2d)

[[12 13 14]
 [15 16 17]
 [18 19 20]]


#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [30]:
arr=np.array([3, 7, 0, 0, 9, 0])
arr1=np.nonzero(arr)
print(arr1)

(array([0, 1, 4]),)


#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [35]:
arr2=np.random.random((2,2,2))
print(arr2)

[[[0.94363707 0.64096055]
  [0.62190836 0.69806878]]

 [[0.25793641 0.00380857]
  [0.88832905 0.80845264]]]


#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [42]:
arr3=np.random.randn(81).reshape(9,9)
max=np.max(arr3)
min=np.min(arr3)
print([max,min])

[3.0194159307629795, -1.8421261117444843]


#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [43]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.7 == 7 * 0.1)

nan
False
False
nan
True
False


#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [45]:
arr4=np.random.randn(6,3)
arr5=np.random.randn(3,4)
power=np.dot(arr4,arr5)
print(power)

[[ 0.00418288 -0.50237884 -0.05905675  0.06912631]
 [-1.76648177 -2.41325361  1.20297603 -1.53414902]
 [-0.68119768 -1.43778309 -0.19113528  0.21411035]
 [ 0.06492658 -1.91706339  1.40725128 -1.75352691]
 [-0.49286628 -1.72726349  1.2728496  -1.59480671]
 [ 0.08829632 -0.81119969  0.3285301  -0.41105532]]


#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [46]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
# bunday bolishini sababi python metodlari numpy metodlari bilan arlashib notogri javob chiqaryapti

9
10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [49]:
a=np.array([1, 2])
b=np.array([4, 5])
result=where(a>=b,False,True)
print(result)

[False False]


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [50]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-50-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
<ipython-input-50-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
<ipython-input-50-2a10de0ee61b>:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [51]:
names1=np.array(['hasan','husan','alisher','bahodir','elshod'])
names2=np.array(['hasan','jasur','alisher','nozim','elshod'])
names=np.intersect1d(names1,names2)
print (names)

['alisher' 'elshod' 'hasan']


#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [63]:
array=np.array([-5.0,4.2,5.3,-4.4,6.01])
print(np.floor(array))
print(array-array%1)
print(array.astype(int))
print(np.trunc(array))


[-5.  4.  5. -5.  6.]
[-5.  4.  5. -5.  6.]
[-5  4  5 -4  6]
[-5.  4.  5. -4.  6.]


#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [65]:
array=(np.arange(0,9)/4).reshape(3,3)
print(array)

[[0.   0.25 0.5 ]
 [0.75 1.   1.25]
 [1.5  1.75 2.  ]]


#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [66]:
a=np.random.randn(10)
b=sort(a)
print(b)

[-2.1610701  -2.00453182 -1.51229299 -0.98968553 -0.91953683 -0.1072516
  0.1484877   0.14995581  0.62224415  0.91364866]


#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [69]:
A=np.random.randn(10)
B=np.random.randn(10)
C=np.allclose(A,B)
print(C)
C=np.array_equal(A,B)
print(C)

False
False


#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [70]:
arr4=np.random.randn(6,3)
arr5=np.random.randn(3,4)
power=np.dot(arr4,arr5)
print(power)

[[-0.40721213  0.14349398  2.34294628 -0.66403612]
 [ 0.39208503  0.75712917  0.82901966  0.2275779 ]
 [-0.22128929 -1.07550461 -2.38080534  0.03369135]
 [ 0.50933611  0.70102412 -0.39426825  0.63673814]
 [-1.27017166 -1.74051585  3.61426936 -2.69642778]
 [ 0.37538262  0.01088932 -2.3909228   0.85362495]]


#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [80]:
a=np.random.randn(5)
max_index=np.argmax(a)
a[max_index]=0
print (a)

[-2.11479932  0.         -0.38168585 -1.24348362 -0.01151244]


#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [83]:
start_date = np.datetime64('2016-01-01')
end_date = np.datetime64('2016-01-31')
dates = np.arange(start_date, end_date + np.timedelta64(1, 'D'), dtype='datetime64[D]')
print(dates)

['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30'
 '2016-01-31']


#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [84]:
array=np.array([5.7,4.2,5.5,3.1,6.9])
print(np.floor(array))
print(array-array%1)
print(array.astype(int))
print(np.trunc(array))


[5. 4. 5. 3. 6.]
[5. 4. 5. 3. 6.]
[5 4 5 3 6]
[5. 4. 5. 3. 6.]


#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [85]:
massiv1 = np.array([1, 2, 3])
massiv2 = np.array([4, 5, 6])
massiv3 = np.array([7, 8, 9])
massivlar = [massiv1, massiv2, massiv3]
yigindi = np.add.reduce(massivlar)
print("Yig'indilar:", yigindi)

Yig'indilar: [12 15 18]


#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [98]:
vektor=np.array([1, 2, 3, 4, 5])
yangi_vektor = np.zeros(len(vektor) * 4 - 3)  # Yangilangan uzunlik
yangi_vektor[::4] = vektor
print(yangi_vektor)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [108]:
from numpy.lib.stride_tricks import as_strided
a =np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
new_a=as_strided(a,shape=(11 ,4),strides=(a.strides[0],a.strides[0]) )
print(new_a)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [4]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 3, 4, 2, 1, 2, 5, 3, 4])
counts = np.bincount(a)
most_common = np.argmax(counts)
print(f"Massiv: {a}")
print(f"Qiymatlar takrorlanishi: {counts}")
print(f"Eng ko'p uchraydigan qiymat: {most_common}")

Massiv: [1 2 3 4 5 3 4 2 1 2 5 3 4]
Qiymatlar takrorlanishi: [0 2 3 3 3 2]
Eng ko'p uchraydigan qiymat: 2


#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`